---
- name: Create web root of sites
  file: path="{{ www_root }}/{{ item.site_name }}/current"
        owner="{{ item.user | default(user) }}"
        group=www-data
        mode=0755
        state=directory
  with_items: node_apps

- name: Create logs folder of sites
  file: path="{{ www_root }}/{{ item.site_name }}/logs"
        owner="{{ item.user | default(user) }}"
        group=www-data
        mode=0755
        state=directory
  with_items: node_apps

- name: Change site owner to user
  file: path="{{ www_root }}/{{ item.site_name }}"
        owner="{{ item.user | default(user) }}"
        group=www-data
        state=directory
        recurse=yes
  with_items: node_apps

- name: Create Node apps configuration for Nginx
  template: src="node-app.conf.j2"
            dest="/etc/nginx/sites-available/{{ item.name }}.conf"
  with_items: node_apps
  when: item.site_hosts is defined

- name: Enable Node app w/Nginx
  file: src="/etc/nginx/sites-available/{{ item.name }}.conf"
        dest="/etc/nginx/sites-enabled/{{ item.name }}.conf"
        owner=root
        group=root
        state=link
  with_items: node_apps
  when: item.site_hosts is defined

- name: Create Upstart script for each app
  template: src=node-upstart.conf.j2 dest=/etc/init/{{ item.site_name }}.conf owner={{ item.user }} group=www-data
  with_items: node_apps