---
- name: Add MariaDB MySQL apt-key
  apt_key: url="http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search={{ keyserver_fingerprint }}"
           state=present

- name: Add MariaDB MySQL deb and deb-src
  apt_repository: repo="{{ item }}" state=present
  with_items:
  - "deb http://{{ mirror }}/mariadb/repo/{{ version }}/ubuntu {{ mariadb_dist | default(ansible_distribution_release) }} main"
  - "deb-src http://{{ mirror }}/mariadb/repo/{{ version }}/ubuntu {{ mariadb_dist | default(ansible_distribution_release) }} main"

- name: Install MariaDB MySQL server
  apt: name=mariadb-server state=present

- name: Start MariaDB MySQL Server
  service: name=mysql state=started enabled=true

- name: Set root user password
  mysql_user: name=root
              password="{{ mysql_root_password }}"
              check_implicit_admin=yes
              login_user="{{ mysql_user }}"
              login_password="{{ mysql_root_password }}"
              state=present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Delete anonymous MySQL server user for current hostname
  mysql_user: user=""
              host="{{ ansible_hostname }}"
              state=absent
              login_user="{{ mysql_user }}"
              login_password="{{ mysql_root_password }}"

- name: Delete anonymous MySQL server user for localhost
  mysql_user: user=""
              state=absent
              login_user="{{ mysql_user }}"
              login_password="{{ mysql_root_password }}"

- name: Remove the test database
  mysql_db: name=test
            state=absent
            login_user="{{ mysql_user }}"
            login_password="{{ mysql_root_password }}"

- name: add /etc/mysql/my.cnf
  template: >
    src=etc-mysql-my.cnf.j2
    dest=/etc/mysql/my.cnf
    owner=root group=root mode=0644
  notify:
    - mysql restart

- name: add /etc/mysql/conf.d directory
  file: >
    path=/etc/mysql/conf.d state=directory
    owner=root group=root mode=0755

- name: add /etc/mysql/conf.d/main.cnf
  template: >
    src=etc-mysql-conf.d-{{ mysqlConfiguration }}.cnf.j2
    dest=/etc/mysql/conf.d/main.cnf
    owner=root group=root mode=0644
  notify:
    - mysql restart

- name: remove extra /etc/mysql/conf.d configurations
  file: >
    path=/etc/mysql/conf.d/{{ item }} state=absent
  with_items:
    - mariadb.cnf
    - tokudb.cnf

- name: ensure mysql owner on /var/lib/mysql
  shell: >
    chown -R mysql: /var/lib/mysql
  changed_when: False

