# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  jeffstieler.com:
    site_hosts:
      - canonical: jeffstieler.test
        redirects:
          - www.jeffstieler.test
    local_path: ../jeffstieler_com # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@example.test
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    site_title: Jeff Stieler [dev]
  utahbeerfinder.com:
    site_hosts:
      - canonical: utahbeerfinder.test
        redirects:
          - www.utahbeerfinder.test
    local_path: ../utah-beer-finder-wp # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@example.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    site_title: Utah Beer Finder [dev]