# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  utahbeerfinder.com:
    site_hosts:
      - canonical: utahbeerfinder.com
        redirects:
          - www.utahbeerfinder.com
    repo: git@github.com:jeffstieler/utah-beer-finder-wp.git # replace with your Git repo URL
    branch: master
    local_path: utah-beer-finder
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
  jeffstieler.com:
    site_hosts:
      - canonical: jeffstieler.com
        redirects:
          - www.jeffstieler.com
    repo: git@github.com:jeffstieler/jeffstieler.com.git # replace with your Git repo URL
    branch: master
    local_path: jeffstieler-com
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
